config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get :new_session, to: "welcome#new"
  post :sign_in, to: "welcome#sign_in"
  resources :books, only: [ :index, :create, :update, :new ] do
    member do
      post :claim
      post :unclaim
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  before_update :sanitize_user_name

  def is_claimed?
    user_name.present?
  end

  def is_claimed_by?(name)
    name == user_name
  end

  private

  def sanitize_user_name
    self.user_name = ActionController::Base.helpers.sanitize(user_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  http_basic_authenticate_with name: Rails.application.credentials.admin_name,
                               password: Rails.application.credentials.admin_password,
                               only: [ :create, :new ]
  before_action :set_user
  before_action :check_authentication, only: [ :claim, :unclaim ]
  before_action :set_book!, only: [ :claim, :unclaim ]
  after_action only: :claim do
    Turbo::StreamsChannel.broadcast_replace_later_to("books",
      target: "claim_#{helpers.dom_id(@book)}",
      partial: "books/claimed",
      locals: { book: @book }
    )
  end
  after_action only: :unclaim do
    Turbo::StreamsChannel.broadcast_replace_later_to("books",
      target: "claimed_#{helpers.dom_id(@book)}",
      partial: "books/claim",
      locals: { book: @book }
    )
  end

  class AuthenticationError < StandardError
  end

  class AuthorizationError < StandardError
  end

  def index
    redirect_to new_session_path and return unless @is_authenticated

    @books = Book.all
  end

  def create
    params[:message].split("\n").each do |line|
      title, author = line.split(",")
      Book.find_or_create_by!(title: title, author: author)
    end
    redirect_to books_path
  end

  def claim
    raise StandardError if @book.is_claimed?

    @book.update!(user_name: @user_name)
    render partial: "form", locals: { book: @book, can_unclaim: @book.is_claimed_by?(@user_name) }
  rescue
    render partial: "error", locals: { book: @book }
  end

  def unclaim
    raise AuthorizationError unless @book.is_claimed_by?(@user_name)

    @book.update!(user_name: nil)
    render partial: "form", locals: { book: @book, can_unclaim: @book.is_claimed_by?(@user_name) }
  rescue
    render partial: "error", locals: { book: @book }
  end

  def new
  end

  private

  def set_book!
    @book = Book.find_by!(id: params[:id])
  end

  def set_user
    @user_name = cookies[:user_name]
    @is_authenticated = @user_name.present?
  end

  def check_authentication
    raise AuthenticationError unless @user_name.present?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def new
  end

  def sign_in
    # TODO: remove numbers etc
    cookies[:user_name] = params[:user_name]
    redirect_to books_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_background.html.haml
%svg{:height => "100%", :width => "100%"}
  %defs
    %pattern.text-slate-200#books-200{:fill => "none", :height => "50", :patternunits => "userSpaceOnUse", :stroke => "currentColor", "stroke-width" => "1.5", :viewbox => "0 0 48 48", :width => "50", :x => "0", :y => "0"}
      %path{:d => "M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25", "stroke-linecap" => "round", "stroke-linejoin" => "round", :transform => "translate(12, 12)"}
    %pattern.text-slate-100#books-100{:fill => "none", :height => "50", :patternunits => "userSpaceOnUse", :stroke => "currentColor", "stroke-width" => "1.5", :viewbox => "0 0 48 48", :width => "50", :x => "0", :y => "0"}
      %path{:d => "M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25", "stroke-linecap" => "round", "stroke-linejoin" => "round", :transform => "translate(12, 12)"}
    %radialgradient#circleGradient{:cx => "50%", :cy => "50%", :r => "10%", :gradientUnits => "userSpaceOnUse"}
      %stop{:offset => "0%", "stop-color" => "white"}
      %stop{:offset => "80%", "stop-color" => "white"}
      %stop{:offset => "100%", "stop-color" => "black"}
    %mask#circleMask
      %rect{:fill => "url(#circleGradient)", :height => "100%", :width => "100%"}
  %rect{:x => "0", :y => "0", :width => "100%", :height => "100%", :fill => "url(#books-100)"}
  %rect.mouse-only.hidden-until-mousemove{:x => "0", :y => "0", :width => "100%", :height => "100%", :fill => "url(#books-200)", :mask => "url(#circleMask)"}

:javascript
  document.addEventListener('mousemove', (event) => {
      const gradient = document.getElementById('circleGradient');
      const { clientX, clientY } = event;

      const cx = (clientX / window.innerWidth) * 100;
      const cy = (clientY / window.innerHeight) * 100;

      setTimeout(() => {
        gradient.setAttribute('cx', `${cx}%`);
        gradient.setAttribute('cy', `${cy}%`);
      }, 100);

  });

app/views/books/_claim.html.haml
%div{id: "claim_#{dom_id(book)}"}
  = button_to "Réserver", claim_book_path(book.id), method: :post, class: 'btn btn-accent btn-sm md:btn-md w-24'

app/views/books/_claimed.html.haml
%div{id: "claimed_#{dom_id(book)}"}
  = button_tag "Réservé", type: 'button', disabled: true, class: 'btn btn-sm md:btn-md cursor-not-allowed w-24 select-none'

app/views/books/_error.html.haml
%turbo-frame{id: dom_id(book)}
  .h-8.w-24.flex.justify-center.items-center
    %svg.size-6{:fill => "none", :stroke => "currentColor", "stroke-width" => "1.5", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
      %path{:d => "M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z", "stroke-linecap" => "round", "stroke-linejoin" => "round"}

app/views/books/_form.html.haml
%turbo-frame{id: dom_id(book)}
  - if book.is_claimed?
    - if can_unclaim
      = link_to "Annuler", unclaim_book_path(book.id), data: { turbo_method: "post" }, class: 'btn btn-outline btn-neutral btn-sm md:btn-md w-24'
    - else
      = render partial: "books/claimed", locals: { book: book }

  - else
    = render partial: "books/claim", locals: { book: book }

app/views/books/index.html.haml
= turbo_stream_from "books"

%h1 Réserve-moi.

.flex.flex-col.gap-2
  - @books.each do |book|
    .flex.flex-row.justify-between.gap-4
      .flex.items-center
        %div.leading-tight
          %span.font-semibold<
            = book.title
            %span.font-normal ,
          %span
            = book.author

      = render partial: "form", locals: { book: book, can_unclaim: book.is_claimed_by?(@user_name) }

app/views/books/new.html.haml
%h1 Books#new
%p Find me in app/views/books/new.html.erb

= form_with url: books_path, method: :post do |form|
  = form.text_area :message, class: "textarea textarea-bordered", size: "70x5", value: (1..20).map { |i| "Test#{i},Author#{i},\n" }.join("")
  = form.submit "Save", class: "btn btn-lg btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Books Giveaway"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    -# %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    -# %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    -# = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"

  %body.h-screen
    .relative.h-full
      .absolute.inset-0.text-slate-100
        = render "background"
      %main.h-full.w-full.z-20.relative.overflow-scroll.py-4.md:py-8
        .h-full.prose.container
          = yield
          .h-16
    :javascript
      function handleMouseMove() {
        document.body.classList.add('mouse-moved');
        document.removeEventListener('mousemove', handleMouseMove);
      }
      document.addEventListener('mousemove', handleMouseMove);

app/views/welcome/index.html.haml
%h1 Salut !

%details
  %summary.cursor-pointer.outline-none.select-none J'ai pas mal de bouquins chez moi.
  = image_tag "books.jpg", style: "max-width: 100%"

%p Je vais m'en séparer !

%p Si tu les veux, fais-toi plaisir.

.flex.justify-center
  = link_to "Réserver un livre", books_path, class: 'btn btn-lg no-underline btn-primary'

app/views/welcome/new.html.haml
%h2 Qui es-tu ?

= form_with url: sign_in_path, local: true, method: :post, class: 'flex flex-col sm:flex-row justify-between gap-4' do |form|
  = form.text_field :user_name, autocomplete: 'given-name', required: true, pattern: ".*[a-zA-Z].*", autofocus: true, class: 'input input-bordered w-full'
  = form.submit "Enregistrer", class: 'btn btn-primary'